# Generated by Django 6.0.7 on 2026-07-20 15:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='aberta', max_length=10)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('recebida_em', models.DateTimeField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_compra', to='suprimentos.fornecedor')),
            ],
            options={
                'verbose_name': 'Ordem de compra',
                'verbose_name_plural': 'Ordens de compra',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.produto')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.ordemcompra')),
            ],
            options={
                'verbose_name': 'Item da ordem de compra',
                'verbose_name_plural': 'Itens da ordem de compra',
            },
        ),
    ]
