# Generated by Django 6.0.7 on 2026-07-23 19:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_movimentacaoestoque_categoria_reserva'),
        ('suprimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('finalizada', 'Finalizada')], default='aberta', max_length=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='itemordemcompra',
            name='quantidade_recebida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordemcompra',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Recebida parcialmente'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='aberta', max_length=10),
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.cotacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Item da cotação',
                'verbose_name_plural': 'Itens da cotação',
                'unique_together': {('cotacao', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='PropostaCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prazo_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo de entrega (dias)')),
                ('observacoes', models.CharField(blank=True, max_length=200)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_cotacao', to='suprimentos.fornecedor')),
                ('item_cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='suprimentos.itemcotacao')),
            ],
            options={
                'verbose_name': 'Proposta de fornecedor',
                'verbose_name_plural': 'Propostas de fornecedores',
                'unique_together': {('item_cotacao', 'fornecedor')},
            },
        ),
    ]
