# Generated by Django 6.0.7 on 2026-07-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0002_cotacao_itemordemcompra_quantidade_recebida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='avaliacao',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], help_text='Sua nota manual sobre esse fornecedor — qualidade, atendimento, confiabilidade.', null=True, verbose_name='Avaliação (1-5 estrelas)'),
        ),
    ]
