# Generated by Django 6.0.7 on 2026-07-25 16:46

import core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0003_fornecedor_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='documento',
            field=core.encrypted_fields.CampoCriptografado(blank=True, max_length=500, verbose_name='CNPJ/CPF'),
        ),
    ]
