# Generated by Django 6.0.7 on 2026-07-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0004_alter_fornecedor_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcompra',
            name='status',
            field=models.CharField(choices=[('pendente_aprovacao', 'Aguardando aprovação'), ('aberta', 'Aberta'), ('parcial', 'Recebida parcialmente'), ('recebida', 'Recebida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
    ]
