# Generated by Django 6.0.7 on 2026-07-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroauditoria',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registroauditoria',
            name='ip',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
