# Generated by Django 6.0.7 on 2026-07-20 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste manual')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU / código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do item')),
                ('edicao', models.CharField(blank=True, max_length=120, verbose_name='Edição / coleção')),
                ('raridade', models.CharField(blank=True, max_length=80, verbose_name='Raridade')),
                ('estado_conservacao', models.CharField(choices=[('mint', 'Mint (M)'), ('near_mint', 'Near Mint (NM)'), ('excellent', 'Excellent (EX)'), ('good', 'Good (GD)'), ('light_played', 'Light Played (LP)'), ('played', 'Played (PL)'), ('poor', 'Poor (PO)'), ('na', 'Não se aplica')], default='na', max_length=20)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de venda')),
                ('estoque_atual', models.PositiveIntegerField(default=0, editable=False)),
                ('estoque_minimo', models.PositiveIntegerField(default=1, verbose_name='Estoque mínimo (alerta)')),
                ('ativo', models.BooleanField(default=True)),
                ('codigo_olist', models.CharField(blank=True, max_length=60, null=True, verbose_name='Código no Olist (referência de integração)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
