# Generated by Django 6.0.7 on 2026-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras (EAN/UPC)'),
        ),
    ]
