# Generated by Django 6.0.7 on 2026-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_produto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='alerta_estoque_enviado',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
