# Generated by Django 6.0.7 on 2026-07-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_produto_alerta_estoque_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='margem_desejada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preencha pra calcular o preço de venda sugerido automaticamente a partir do custo.', max_digits=5, null=True, verbose_name='Margem desejada (%)'),
        ),
    ]
