# Generated by Django 6.0.7 on 2026-07-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_produto_margem_desejada'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='grading_certificado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número do certificado/slab'),
        ),
        migrations.AddField(
            model_name='produto',
            name='grading_empresa',
            field=models.CharField(blank=True, choices=[('', 'Sem grading'), ('PSA', 'PSA'), ('BGS', 'BGS (Beckett)'), ('CGC', 'CGC'), ('SGC', 'SGC')], max_length=10, verbose_name='Empresa de grading'),
        ),
        migrations.AddField(
            model_name='produto',
            name='grading_nota',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Ex: 9.5, 10.0', max_digits=3, null=True, verbose_name='Nota do grading'),
        ),
    ]
