# Generated by Django 6.0.7 on 2026-07-22 20:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_produto_grading_certificado_produto_grading_empresa_and_more'),
        ('suprimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='altura_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Código próprio de organização interna, separado do SKU (opcional).', max_length=50, verbose_name='Código interno'),
        ),
        migrations.AddField(
            model_name='produto',
            name='comprimento_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Comprimento (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo de frete (rateado, R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Impostos (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='ean',
            field=models.CharField(blank=True, help_text='Código EAN original do fabricante, quando existir.', max_length=20, null=True, unique=True, verbose_name='EAN de fábrica'),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Referência de capacidade ideal — não bloqueia entradas.', null=True, verbose_name='Estoque máximo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, help_text='Fornecedor padrão desse item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_catalogo', to='suprimentos.fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='idioma',
            field=models.CharField(blank=True, choices=[('pt', 'Português'), ('en', 'Inglês'), ('jp', 'Japonês'), ('es', 'Espanhol'), ('outro', 'Outro')], max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='largura_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Largura (cm)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: Prateleira A3, Gaveta 2.', max_length=100, verbose_name='Localização física'),
        ),
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, max_length=60, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='produto',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de série'),
        ),
        migrations.AddField(
            model_name='produto',
            name='peso_gramas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (g)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alerta no PDV se tentar vender abaixo desse valor.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço mínimo de venda (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_composicao',
            field=models.CharField(choices=[('simples', 'Produto simples (não composto)'), ('kit', 'Kit'), ('combo', 'Combo'), ('bundle', 'Bundle'), ('caixa', 'Caixa'), ('booster_box', 'Booster Box'), ('blister', 'Blister'), ('etb', 'ETB (Elite Trainer Box)'), ('case', 'Case')], default='simples', help_text='Só informativo pra produtos simples. Pra produto composto de verdade, cadastre os componentes abaixo.', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, null=True, verbose_name='Data de validade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras (interno/impresso)'),
        ),
        migrations.CreateModel(
            name='ComponenteProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parte_de_composicoes', to='catalogo.produto')),
                ('produto_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_kit', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Componente do produto',
                'verbose_name_plural': 'Componentes do produto',
                'unique_together': {('produto_pai', 'produto_componente')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='usado_em_composicoes', through='catalogo.ComponenteProduto', through_fields=('produto_pai', 'produto_componente'), to='catalogo.produto'),
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoria',
                'verbose_name_plural': 'Subcategorias',
                'ordering': ['categoria__nome', 'nome'],
                'unique_together': {('categoria', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='catalogo.subcategoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='produtos', to='catalogo.tag'),
        ),
    ]
