# Generated by Django 6.0.7 on 2026-07-22 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_tag_produto_altura_cm_produto_codigo_interno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('aberta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios_abertos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, help_text='Deixe em branco pra conferir todos os produtos ativos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Sessão de inventário',
                'verbose_name_plural': 'Sessões de inventário',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_esperada', models.PositiveIntegerField()),
                ('quantidade_contada', models.PositiveIntegerField(blank=True, null=True)),
                ('contado_em', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_inventario', to='catalogo.produto')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='catalogo.inventariosessao')),
            ],
            options={
                'verbose_name': 'Item de inventário',
                'verbose_name_plural': 'Itens de inventário',
                'unique_together': {('sessao', 'produto')},
            },
        ),
    ]
