# Generated by Django 6.0.7 on 2026-07-22 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_inventariosessao_iteminventario'),
        ('vendas', '0007_cupomdesconto_cliente_saldo_credito_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='categoria',
            field=models.CharField(blank=True, choices=[('', '—'), ('perda', 'Perda'), ('quebra', 'Quebra'), ('dano', 'Produto danificado'), ('roubo', 'Roubo/furto'), ('vencido', 'Vencido'), ('outro', 'Outro motivo de baixa')], max_length=10, verbose_name='Categoria (só pra baixas de perda/quebra/dano)'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('validade', models.DateField(blank=True, help_text='Deixe em branco pra reserva sem prazo. Depois dessa data, ela deixa de contar como estoque reservado.', null=True, verbose_name='Reservado até')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('atendida', 'Atendida (virou venda)'), ('cancelada', 'Cancelada')], default='ativa', max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='vendas.cliente')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-criada_em'],
            },
        ),
    ]
