# Generated by Django 6.0.7 on 2026-07-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_movimentacaoestoque_categoria_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='jogo_tcg',
            field=models.CharField(blank=True, choices=[('', 'Nenhum (não busca imagem automática)'), ('pokemon', 'Pokémon'), ('magic', 'Magic: The Gathering'), ('yugioh', 'Yu-Gi-Oh!')], help_text='Se marcado, produtos dessa categoria ganham o botão de buscar imagem automaticamente.', max_length=10, verbose_name='Jogo (pra busca automática de imagem)'),
        ),
    ]
