# Generated by Django 6.0.7 on 2026-07-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_categoria_jogo_tcg'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foil',
            field=models.BooleanField(default=False, verbose_name='Foil'),
        ),
        migrations.AddField(
            model_name='produto',
            name='numero_colecao',
            field=models.CharField(blank=True, help_text='Ex: 025/198 — o número impresso na carta dentro do set.', max_length=20, verbose_name='Número na coleção'),
        ),
        migrations.AddField(
            model_name='produto',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Promo'),
        ),
        migrations.AddField(
            model_name='produto',
            name='reverse_holo',
            field=models.BooleanField(default=False, verbose_name='Reverse holo'),
        ),
    ]
