# Generated by Django 6.0.7 on 2026-07-25 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_produto_foil_produto_numero_colecao_produto_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Referência de teto — útil pra cartas com preço muito volátil.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço máximo de venda (R$)'),
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_novo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Histórico de preço',
                'verbose_name_plural': 'Histórico de preços',
                'ordering': ['-alterado_em'],
            },
        ),
    ]
