# Generated by Django 6.0.7 on 2026-07-20 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Sempre o primeiro dia do mês, ex: 01/08/2026 pra meta de agosto.', unique=True, verbose_name='Mês (use o dia 1)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta de faturamento (R$)')),
            ],
            options={
                'verbose_name': 'Meta mensal',
                'verbose_name_plural': 'Metas mensais',
                'ordering': ['-mes'],
            },
        ),
    ]
