# Generated by Django 6.0.7 on 2026-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_produto_parado', models.PositiveIntegerField(default=60, verbose_name="Considerar 'parado' sem vender há quantos dias")),
            ],
            options={
                'verbose_name': 'Configuração de estoque',
                'verbose_name_plural': 'Configuração de estoque',
            },
        ),
    ]
