# Generated by Django 6.0.7 on 2026-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_preferenciadashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRelatorioAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Enviar resumo automático por e-mail')),
                ('frequencia', models.CharField(choices=[('semanal', 'Semanal (toda segunda-feira)'), ('mensal', 'Mensal (todo dia 1º)')], default='semanal', max_length=10)),
                ('destinatario', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de destino')),
                ('ultimo_envio', models.DateField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Configuração de relatório automático',
                'verbose_name_plural': 'Configuração de relatório automático',
            },
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='reposicao_automatica_ativa',
            field=models.BooleanField(default=False, help_text='Só funciona pra produtos que já têm um fornecedor padrão definido na ficha.', verbose_name='Gerar ordem de compra sozinho quando o estoque bater no mínimo'),
        ),
        migrations.AddField(
            model_name='configuracaoestoque',
            name='reposicao_multiplicador_minimo',
            field=models.PositiveIntegerField(default=3, help_text="Usado quando o produto não tem 'estoque máximo' definido.", verbose_name='Quantidade sugerida = estoque mínimo × este número'),
        ),
    ]
