# Generated by Django 6.0.7 on 2026-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0004_configuracaorelatorioautomatico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaorelatorioautomatico',
            name='frequencia',
            field=models.CharField(choices=[('diario', 'Diário (todo dia)'), ('semanal', 'Semanal (toda segunda-feira)'), ('mensal', 'Mensal (todo dia 1º)'), ('anual', 'Anual (todo dia 1º de janeiro)')], default='semanal', max_length=10),
        ),
    ]
