# Generated by Django 6.0.7 on 2026-07-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_criar_views_bi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('manual', 'Download manual'), ('agendado_local', 'Agendado (local)'), ('agendado_email', 'Agendado (e-mail)')], default='manual', max_length=20)),
            ],
            options={
                'verbose_name': 'Registro de backup',
                'verbose_name_plural': 'Registros de backup',
                'ordering': ['-criado_em'],
            },
        ),
    ]
