# Generated by Django 6.0.7 on 2026-07-21 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('sucesso', models.BooleanField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentativa de login',
                'verbose_name_plural': 'Tentativas de login',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DoisFatores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=32)),
                ('ativado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dois_fatores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autenticação em duas etapas',
                'verbose_name_plural': 'Autenticação em duas etapas',
            },
        ),
    ]
