# Generated by Django 6.0.7 on 2026-07-25 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('seguranca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Área do sistema',
                'verbose_name_plural': 'Áreas do sistema',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso_total', models.BooleanField(default=False, verbose_name='Acesso total (todas as áreas, inclusive futuras)')),
                ('areas', models.ManyToManyField(blank=True, to='seguranca.area')),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_acesso', to='auth.group')),
            ],
            options={
                'verbose_name': 'Perfil de acesso',
                'verbose_name_plural': 'Perfis de acesso',
            },
        ),
        migrations.CreateModel(
            name='SessaoAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('dispositivo', models.CharField(blank=True, max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_ativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão ativa',
                'verbose_name_plural': 'Sessões ativas',
                'ordering': ['-ultima_atividade'],
            },
        ),
    ]
