# Generated by Django 6.0.7 on 2026-07-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguranca', '0002_area_perfilacesso_sessaoativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=45, unique=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'IP bloqueado',
                'verbose_name_plural': 'IPs bloqueados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
