# Generated by Django 6.0.7 on 2026-07-27 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Ordem de compra'), ('pagamento', 'Conta a pagar'), ('desconto', 'Desconto de venda no PDV')], max_length=15, unique=True)),
                ('ativa', models.BooleanField(default=False, verbose_name='Exigir aprovação pra esse tipo')),
                ('valor_limite', models.DecimalField(decimal_places=2, default=0, help_text='Pra desconto, esse valor é em R$ (desconto absoluto na venda), não percentual.', max_digits=10, verbose_name='A partir de que valor exige aprovação')),
            ],
            options={
                'verbose_name': 'Regra de aprovação',
                'verbose_name_plural': 'Regras de aprovação',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('compra', 'Ordem de compra'), ('pagamento', 'Conta a pagar'), ('desconto', 'Desconto de venda no PDV')], max_length=15)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_atual', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de aprovação',
                'verbose_name_plural': 'Solicitações de aprovação',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDecisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField()),
                ('decisao', models.CharField(choices=[('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], max_length=10)),
                ('comentario', models.TextField(blank=True)),
                ('decidido_em', models.DateTimeField(auto_now_add=True)),
                ('aprovador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='aprovacoes.solicitacaoaprovacao')),
            ],
            options={
                'verbose_name': 'Registro de decisão',
                'verbose_name_plural': 'Registros de decisão',
                'ordering': ['decidido_em'],
            },
        ),
        migrations.CreateModel(
            name='NivelAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField()),
                ('grupo_aprovador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis', to='aprovacoes.regraaprovacao')),
            ],
            options={
                'verbose_name': 'Nível de aprovação',
                'verbose_name_plural': 'Níveis de aprovação',
                'ordering': ['regra', 'ordem'],
                'unique_together': {('regra', 'ordem')},
            },
        ),
    ]
