# Generated by Django 6.0.7 on 2026-07-20 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('processada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('processada_em', models.DateTimeField(blank=True, null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.devolucao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.produto')),
            ],
            options={
                'verbose_name': 'Item da devolução',
                'verbose_name_plural': 'Itens da devolução',
            },
        ),
    ]
