# Generated by Django 6.0.7 on 2026-07-20 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_devolucao_itemdevolucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de débito'), ('credito_avista', 'Cartão de crédito à vista'), ('credito_parcelado', 'Cartão de crédito parcelado')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('parcelas', models.PositiveSmallIntegerField(default=1)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Pagamento da venda',
                'verbose_name_plural': 'Pagamentos da venda',
            },
        ),
    ]
