# Generated by Django 6.0.7 on 2026-07-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_vendedor_perfilvendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='canal',
            field=models.CharField(choices=[('fisica', 'Loja física'), ('online', 'Online')], default='fisica', max_length=10),
        ),
    ]
