# Generated by Django 6.0.7 on 2026-07-21 20:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Programa de fidelidade ativo')),
                ('valor_por_ponto', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cliente ganha 1 ponto a cada R$ gastos')),
                ('valor_resgate_ponto', models.DecimalField(decimal_places=2, default=Decimal('0.10'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cada ponto vale quanto de desconto (R$)')),
            ],
            options={
                'verbose_name': 'Configuração de fidelidade',
                'verbose_name_plural': 'Configuração de fidelidade',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='pontos_fidelidade',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='pontos_resgatados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
