# Generated by Django 6.0.7 on 2026-07-22 13:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_configuracaofidelidade_cliente_pontos_fidelidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Valor fixo (R$)')], default='percentual', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor (% ou R$, conforme o tipo)')),
                ('ativo', models.BooleanField(default=True)),
                ('validade', models.DateField(blank=True, help_text='Deixe em branco pra não expirar.', null=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Deixe em branco pra uso ilimitado.', null=True)),
                ('usos_atuais', models.PositiveIntegerField(default=0, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom de desconto',
                'verbose_name_plural': 'Cupons de desconto',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=10, verbose_name='Saldo de crédito/cashback (R$)'),
        ),
        migrations.AddField(
            model_name='configuracaofidelidade',
            name='percentual_cashback',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deixe 0 pra desativar o cashback.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cashback (% do valor da compra vira crédito pro cliente)'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Desconto no item (R$)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='acrescimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Acréscimo (R$)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='credito_usado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Crédito/cashback usado nessa venda (R$)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagamentovenda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de débito'), ('credito_avista', 'Cartão de crédito à vista'), ('credito_parcelado', 'Cartão de crédito parcelado'), ('vale', 'Vale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de débito'), ('credito_avista', 'Cartão de crédito à vista'), ('credito_parcelado', 'Cartão de crédito parcelado'), ('vale', 'Vale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aberta', 'Aberta'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='vendas.cupomdesconto'),
        ),
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales', to='vendas.cliente')),
            ],
            options={
                'verbose_name': 'Vale',
                'verbose_name_plural': 'Vales',
            },
        ),
        migrations.AddField(
            model_name='pagamentovenda',
            name='vale',
            field=models.ForeignKey(blank=True, help_text="Preenchido só quando a forma de pagamento é 'Vale'.", null=True, on_delete=django.db.models.deletion.PROTECT, to='vendas.vale'),
        ),
    ]
