# Generated by Django 6.0.7 on 2026-07-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_cupomdesconto_cliente_saldo_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='anonimizado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='Na lista de restrição'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='blacklist_motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='consentimento_dados',
            field=models.BooleanField(default=False, verbose_name='Consentiu com o uso dos dados (LGPD)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='consentimento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
