# Generated by Django 6.0.7 on 2026-07-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_cliente_anonimizado_cliente_bairro_cliente_blacklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='mensagem_posvenda_enviada',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
