# Generated by Django 6.0.7 on 2026-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_alter_cliente_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='mensagem_recuperacao_enviada',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
