# Generated by Django 6.0.7 on 2026-07-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0011_venda_mensagem_recuperacao_enviada'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaOfflinePendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_offline', models.CharField(max_length=40, unique=True)),
                ('payload_json', models.TextField()),
                ('erro', models.TextField(blank=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venda offline pendente',
                'verbose_name_plural': 'Vendas offline pendentes',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='uuid_offline',
            field=models.CharField(blank=True, help_text='Preenchido só quando a venda foi feita no modo offline do PDV — evita duplicar ao sincronizar.', max_length=40, null=True, unique=True),
        ),
    ]
