# Generated by Django 6.0.7 on 2026-07-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_vendaofflinependente_venda_uuid_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aberta', 'Aberta'), ('pendente_aprovacao', 'Aguardando aprovação de desconto'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
    ]
