# Generated by Django 6.0.7 on 2026-07-20 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
            ],
            options={
                'verbose_name': 'Categoria financeira',
                'verbose_name_plural': 'Categorias financeiras',
                'ordering': ['tipo', 'nome'],
                'unique_together': {('nome', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('fornecedor', models.CharField(blank=True, max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vencimento', models.DateField()),
                ('recorrente', models.BooleanField(default=False, verbose_name='Despesa fixa recorrente (mensal)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'despesa'}, on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriafinanceira')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=10)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'receita'}, on_delete=django.db.models.deletion.PROTECT, to='financeiro.categoriafinanceira')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.cliente')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Conta a receber',
                'verbose_name_plural': 'Contas a receber',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contapagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contareceber')),
            ],
            options={
                'verbose_name': 'Movimento de caixa',
                'verbose_name_plural': 'Movimentos de caixa',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
