# Generated by Django 6.0.7 on 2026-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_caixasessao_movimentocaixa_sessao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='grupo_parcelamento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='linha_digitavel',
            field=models.CharField(blank=True, max_length=60, verbose_name='Linha digitável'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='meio_pagamento',
            field=models.CharField(blank=True, choices=[('', '—'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('boleto', 'Boleto'), ('ted', 'TED'), ('doc', 'DOC'), ('transferencia', 'Transferência bancária'), ('cartao', 'Cartão'), ('cheque', 'Cheque'), ('outro', 'Outro')], max_length=15, verbose_name='Meio de pagamento'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_boleto',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número do boleto / nosso número'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcela_numero',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcela_total',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='proxima_gerada',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='grupo_parcelamento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='linha_digitavel',
            field=models.CharField(blank=True, max_length=60, verbose_name='Linha digitável'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='meio_pagamento',
            field=models.CharField(blank=True, choices=[('', '—'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('boleto', 'Boleto'), ('ted', 'TED'), ('doc', 'DOC'), ('transferencia', 'Transferência bancária'), ('cartao', 'Cartão'), ('cheque', 'Cheque'), ('outro', 'Outro')], max_length=15, verbose_name='Meio de pagamento'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='numero_boleto',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número do boleto / nosso número'),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='parcela_numero',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='parcela_total',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='recorrente',
            field=models.BooleanField(default=False, verbose_name='Despesa fixa recorrente (gera a próxima automaticamente ao pagar)'),
        ),
    ]
