# Generated by Django 6.0.7 on 2026-07-24 12:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_contapagar_grupo_parcelamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Como você quer identificar essa conta, ex: 'Nubank PJ'.", max_length=100)),
                ('banco', models.CharField(blank=True, max_length=100)),
                ('agencia', models.CharField(blank=True, max_length=20)),
                ('numero_conta', models.CharField(blank=True, max_length=30)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta bancária',
                'verbose_name_plural': 'Contas bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='conciliado',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='financeiro.contabancaria'),
        ),
        migrations.CreateModel(
            name='LinhaExtratoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10)),
                ('fitid', models.CharField(blank=True, max_length=100, verbose_name='ID da transação no banco (FITID)')),
                ('conciliado', models.BooleanField(default=False)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_extrato', to='financeiro.contabancaria')),
                ('movimento_vinculado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linha_extrato_vinculada', to='financeiro.movimentocaixa')),
            ],
            options={
                'verbose_name': 'Linha de extrato importado',
                'verbose_name_plural': 'Linhas de extrato importado',
                'ordering': ['-data'],
            },
        ),
    ]
