# Generated by Django 6.0.7 on 2026-07-24 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_contabancaria_movimentocaixa_conciliado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='tipo',
            field=models.CharField(choices=[('corrente', 'Conta corrente'), ('poupanca', 'Poupança'), ('outra', 'Outra')], default='corrente', max_length=10),
        ),
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fitid', models.CharField(blank=True, max_length=100, verbose_name='Identificador da transação (FITID do OFX)')),
                ('conciliado', models.BooleanField(default=False)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='financeiro.contabancaria')),
                ('movimento_caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos_conciliados', to='financeiro.movimentocaixa')),
            ],
            options={
                'verbose_name': 'Linha de extrato bancário',
                'verbose_name_plural': 'Extrato bancário',
                'ordering': ['-data'],
                'unique_together': {('conta_bancaria', 'fitid')},
            },
        ),
        migrations.DeleteModel(
            name='LinhaExtratoImportado',
        ),
    ]
