# Generated by Django 6.0.7 on 2026-07-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_contabancaria_tipo_extratobancario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Enviar cobrança automática de conta vencida')),
                ('dias_apos_vencimento', models.PositiveIntegerField(default=3, verbose_name='Enviar a partir de quantos dias vencida')),
                ('intervalo_entre_cobrancas_dias', models.PositiveIntegerField(default=7, verbose_name='Intervalo mínimo entre cobranças da mesma conta (dias)')),
                ('mensagem', models.TextField(default='Oi {nome}! Notei que a conta "{descricao}" no valor de R$ {valor} venceu em {vencimento}. Pode dar uma olhada quando puder? Qualquer dúvida, é só chamar!')),
            ],
            options={
                'verbose_name': 'Configuração de cobrança',
                'verbose_name_plural': 'Configuração de cobrança',
            },
        ),
        migrations.AddField(
            model_name='contareceber',
            name='ultima_cobranca_enviada',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
