# Generated by Django 6.0.7 on 2026-07-24 20:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0009_venda_mensagem_posvenda_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posvenda_ativo', models.BooleanField(default=False, verbose_name='Enviar mensagem de pós-venda automaticamente')),
                ('posvenda_dias', models.PositiveIntegerField(default=7, verbose_name='Dias após a venda')),
                ('posvenda_mensagem', models.TextField(default='Oi {nome}! Passando pra saber se você curtiu sua compra na Belletti Cards Universe. Qualquer coisa, é só chamar! 🎴')),
                ('aniversario_ativo', models.BooleanField(default=False, verbose_name='Enviar mensagem de aniversário automaticamente')),
                ('aniversario_mensagem', models.TextField(default='Feliz aniversário, {nome}! 🎉 A Belletti Cards Universe deseja um dia incrível pra você!')),
                ('lead_parado_ativo', models.BooleanField(default=False, verbose_name='Criar tarefa automática pra lead parado')),
                ('lead_parado_dias', models.PositiveIntegerField(default=5, verbose_name='Dias sem interação')),
            ],
            options={
                'verbose_name': 'Configuração do CRM',
                'verbose_name_plural': 'Configuração do CRM',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('origem', models.CharField(choices=[('indicacao', 'Indicação'), ('redes_sociais', 'Redes sociais'), ('loja_fisica', 'Loja física'), ('evento', 'Evento/torneio'), ('site', 'Site/online'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('etapa', models.CharField(choices=[('novo', 'Novo lead'), ('contato', 'Em contato'), ('negociacao', 'Negociação'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='novo', max_length=15)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor estimado do negócio (R$)')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Preenchido automaticamente quando o lead é convertido em cliente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_origem', to='vendas.cliente')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('presencial', 'Presencial'), ('outro', 'Outro')], default='outro', max_length=12)),
                ('descricao', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='vendas.cliente')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Interação de contato',
                'verbose_name_plural': 'Interações de contato',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('expirada', 'Expirada')], default='aberta', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='vendas.cliente')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Proposta',
                'verbose_name_plural': 'Propostas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_vencimento', models.DateTimeField()),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('gerada_automaticamente', models.BooleanField(default=False, editable=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='vendas.cliente')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='crm.lead')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
