# Generated by Django 6.0.7 on 2026-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocrm',
            name='recuperacao_carrinho_ativa',
            field=models.BooleanField(default=False, verbose_name='Enviar WhatsApp/e-mail pra pedido em andamento esquecido'),
        ),
        migrations.AddField(
            model_name='configuracaocrm',
            name='recuperacao_carrinho_horas',
            field=models.PositiveIntegerField(default=3, verbose_name='Enviar depois de quantas horas em aberto'),
        ),
        migrations.AddField(
            model_name='configuracaocrm',
            name='recuperacao_carrinho_mensagem',
            field=models.TextField(default='Oi {nome}! Vi que você começou uma compra na Belletti Cards Universe e não finalizou. Ainda tem interesse? Posso ajudar a fechar! 🎴'),
        ),
    ]
