# Generated by Django 6.0.7 on 2026-07-29 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_configuracaocrm_recuperacao_carrinho_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cor', models.CharField(default='#8b6cf2', help_text='Código da cor em hexadecimal, ex: #8b6cf2 (pode copiar de um seletor de cor online)', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria da agenda',
                'verbose_name_plural': 'Categorias da agenda',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='crm.categoriatarefa'),
        ),
    ]
