# Generated by Django 6.0.7 on 2026-07-21 15:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(blank=True, max_length=254, verbose_name='E-mail pra receber alertas')),
                ('ativar_email', models.BooleanField(default=True, verbose_name='Ativar alertas por e-mail')),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Formato internacional, ex: +5511999999999. Requer conta Twilio configurada (veja o README).', max_length=20, verbose_name='WhatsApp pra receber alertas')),
                ('ativar_whatsapp', models.BooleanField(default=False, verbose_name='Ativar alertas por WhatsApp')),
                ('limite_diferenca_caixa', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alertar se a diferença no fechamento de caixa passar de (R$)')),
                ('dias_aviso_vencimento', models.PositiveIntegerField(default=2, verbose_name='Avisar sobre contas vencendo em quantos dias')),
            ],
            options={
                'verbose_name': 'Configuração de notificações',
                'verbose_name_plural': 'Configuração de notificações',
            },
        ),
    ]
