# Generated by Django 6.0.7 on 2026-07-27 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_publica', models.TextField(blank=True)),
                ('chave_privada', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração de notificações push',
                'verbose_name_plural': 'Configuração de notificações push',
            },
        ),
        migrations.CreateModel(
            name='InscricaoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh_key', models.CharField(max_length=255)),
                ('auth_key', models.CharField(max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição push',
                'verbose_name_plural': 'Inscrições push',
            },
        ),
    ]
