# Generated by Django 6.0.7 on 2026-07-27 18:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0013_alter_venda_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ordem_exibicao', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria do cardápio',
                'verbose_name_plural': 'Categorias do cardápio',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acompanhamento', models.CharField(default=uuid.uuid4, editable=False, max_length=40, unique=True)),
                ('nome_para_chamar', models.CharField(blank=True, max_length=80, verbose_name='Nome (pra chamar quando ficar pronto)')),
                ('mesa_ou_local', models.CharField(blank=True, help_text='Ex: Mesa 3, Balcão, Retirada', max_length=40)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('em_preparo', 'Em preparo'), ('pronto', 'Pronto'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=12)),
                ('prioridade', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Alta'), (3, 'Urgente')], default=1)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('em_preparo_em', models.DateTimeField(blank=True, null=True)),
                ('pronto_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_cozinha', to='vendas.cliente')),
            ],
            options={
                'verbose_name': 'Pedido da cozinha',
                'verbose_name_plural': 'Pedidos da cozinha',
                'ordering': ['-prioridade', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('foto', models.ImageField(blank=True, upload_to='pratos/%Y/%m/')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível no cardápio agora')),
                ('tempo_preparo_min', models.PositiveIntegerField(default=10, verbose_name='Tempo estimado de preparo (minutos)')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pratos', to='cozinha.categoriaprato')),
            ],
            options={
                'verbose_name': 'Prato',
                'verbose_name_plural': 'Pratos',
                'ordering': ['categoria__ordem_exibicao', 'ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCozinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação (ex: sem cebola)')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cozinha.pedidocozinha')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cozinha.prato')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
