# Generated by Django 6.0.7 on 2026-07-27 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0001_initial'),
        ('vendas', '0013_alter_venda_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nome', models.CharField(blank=True, help_text="Ex: 'Mesa da janela' (opcional, só número já basta)", max_length=50)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ativa', models.BooleanField(default=True, verbose_name='Aceitando pedidos')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='pedidocozinha',
            name='dispositivo',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='pedidocozinha',
            name='ip',
            field=models.CharField(blank=True, editable=False, max_length=45),
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta_em', models.DateTimeField(auto_now_add=True)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=10)),
                ('fechada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comanda_origem', to='vendas.venda')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='cozinha.mesa')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-aberta_em'],
            },
        ),
        migrations.AddField(
            model_name='pedidocozinha',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='cozinha.comanda'),
        ),
        migrations.CreateModel(
            name='ChamadoAtendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('atendente', 'Chamar atendente'), ('talheres', 'Pedir talheres'), ('guardanapo', 'Pedir guardanapo'), ('gelo', 'Pedir gelo'), ('fechamento', 'Solicitar fechamento da conta')], default='atendente', max_length=12)),
                ('atendido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='cozinha.mesa')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='pedidocozinha',
            name='mesa',
            field=models.ForeignKey(blank=True, help_text='Preenchido sozinho quando o pedido vem do QR code de uma mesa específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_diretos', to='cozinha.mesa'),
        ),
    ]
