# Generated by Django 6.0.7 on 2026-07-28 04:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cozinha', '0005_mesa_inteligente_promocoes_avaliacoes'),
        ('vendas', '0013_alter_venda_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionalPrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('preco_extra', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponivel', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='cozinha.prato')),
            ],
            options={
                'verbose_name': 'Adicional do prato',
                'verbose_name_plural': 'Adicionais do prato',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FechamentoComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, help_text="Ex: 'Parte 1 de 3' ou o nome da pessoa", max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos', to='cozinha.comanda')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Fechamento da comanda',
                'verbose_name_plural': 'Fechamentos da comanda',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('preco_extra', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adicional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cozinha.adicionalprato')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais_escolhidos', to='cozinha.itempedidocozinha')),
            ],
            options={
                'verbose_name': 'Adicional escolhido',
                'verbose_name_plural': 'Adicionais escolhidos',
            },
        ),
    ]
